
// Don't touch the below code

(function() {
  function buildQuiz() {
    // we'll need a place to store the HTML output
    const output = [];

    // for each question...
    myQuestions.forEach((currentQuestion, questionNumber) => {
      // we'll want to store the list of answer choices
      const answers = [];

      // and for each available answer...
      for (letter in currentQuestion.answers) {
        // ...add an HTML radio button
        answers.push(
          `<label>
            <input type="radio" name="question${questionNumber}" value="${letter}">
            ${letter} :
            ${currentQuestion.answers[letter]}
          </label>`
        );
      }

      // add this question and its answers to the output
      output.push(
        `<div class="question"> ${currentQuestion.question} </div>
        <div class="answers"> ${answers.join("")} </div>`
      );
    });

    // finally combine our output list into one string of HTML and put it on the page
    quizContainer.innerHTML = output.join("");
  }

  function showResults() {
    // gather answer containers from our quiz
    const answerContainers = quizContainer.querySelectorAll(".answers");

    // keep track of user's answers
    let numCorrect = 0;

    // for each question...
    myQuestions.forEach((currentQuestion, questionNumber) => {
      // find selected answer
      const answerContainer = answerContainers[questionNumber];
      const selector = `input[name=question${questionNumber}]:checked`;
      const userAnswer = (answerContainer.querySelector(selector) || {}).value;

      // if answer is correct
      if (userAnswer === currentQuestion.correctAnswer) {
        // add to the number of correct answers
        numCorrect++;

        // color the answers green
        //answerContainers[questionNumber].style.color = "lightgreen";
      } else {
        // if answer is wrong or blank
        // color the answers red
        answerContainers[questionNumber].style.color = "red";
      }
    });

    // show number of correct answers out of total
    resultsContainer.innerHTML = `${numCorrect} out of ${myQuestions.length}`;
  }

  const quizContainer = document.getElementById("quiz");
  const resultsContainer = document.getElementById("results");
  const submitButton = document.getElementById("submit");
  

// Don't touch the above code




// Write your MCQs here --- Start --- --------------------

  const myQuestions = [
    {
      question: " A narrow-band FM signal which is generated by a 6 KHz signal modulating a 100 MHz carrier. The bandwidth of the narrow FM signal is?",
      answers: {
        a: " 12 KHz",
        b: " 6 KHz",
        c: " 60 KHz",
        d: " 120 KHz"
      },
      correctAnswer: "a"
    },

    {
      question: "On which factor the bandwidth required for a modulated carrier depends?",
      answers: {
        a: " signal to noise ratio",
        b: " carrier frequency",
        c: " baseband frequency range",
        d: " amplitude of carrier frequency"
      },
      correctAnswer: "c"
    },

    {
      question: "Two signals of 2 GHz and 4 GHz frequency modulated on the same carrier of 12 GHz. Find the ratio of frequency deviations if the bandwidths of both are equal",
      answers: {
        a: "1:1",
        b: "1:2",
        c: "2:1",
        d: "1:4"
      },
      correctAnswer: "a"
    },

    
    {
      question: "Modulation is done in _______",
      answers: {
        a: "Radio receiver",
        b: "Transmitter",
        c: "Between transmitter and radio receiver",
        d: "None of the options"
      },
      correctAnswer: "b"
    },

    {
      question: "In an FM wave useful power is carrier by ______ ",
      answers: {
        a: "Carrier",
        b: "Sidebands",
        c: "Both sidebands and carrier",
        d: "None of the options"
      },
      correctAnswer: "c"
    },
  ];




// ---------------------------- End -------------------------------








  // display quiz right away
  buildQuiz();

  // on submit, show results
  submitButton.addEventListener("click", showResults);
})();
